services:
  apache: # nama service
    image: tomsik68/xampp:latest # Nama image sumber
    container_name: xampp-apache
    ports:
      - "8080:80" # Akses Apache melalui port 8080
      - "443:443" # Akses HTTPS jika diperlukan
    volumes:
      - "./htdocs:/www/htdocs" # Direktori proyek lokal
      # - ./logs:/www/logs # Direktori log lokal
      # - ./config:/www/config # Direktori konfigurasi lokal
    networks:
      - xampp-network
    depends_on: # fungsi = menunggu service database start terlebih dahulu
      - database

  phpmyadmin: # nama service
    image: phpmyadmin:latest # Nama image sumber
    container_name: phpmyadmin
    ports:
      - "8081:80" # Akses phpMyAdmin melalui port 8081
    environment:
      PMA_HOST: database # Nama service database # pastikan sama
      PMA_USER: root
      PMA_PASSWORD: example # harus sama dengan MYSQL_ROOT_PASSWORD
    depends_on: # fungsi = menunggu service database start terlebih dahulu
      - database
    networks:
      - xampp-network

  database: # nama service # docker-compose up -d database
    image: mysql:5.7 # Nama image sumber
    container_name: mysql-database # Nama container dari kita
    # restart: always # restart jika container mati # docker restart mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - "db_data:/var/lib/mysql"
      # - "./backup:/data" # data yang akan di inport ke db
    networks:
      - xampp-network

networks:
  xampp-network:
    driver: bridge
    name: xampp-network

volumes:
  db_data: # key volume
    name: db_xampp # nama volume
